Сделал сортировку
htmlacademy-ecmascript/1410513-big-trip-13 pull request #10
Opened 2020-12-10 21:16 UTC by nelder9

Сделал сортировку

2020-12-12 10:55 UTC, abeluzhenko requested changes

2020-12-12 10:55 UTC, abeluzhenko commented on src/utils/render.js
> +export const renderPosition = {
Здесь было правильно `RenderPosition`, это enum, по критериям он должен быть в `PascalCase`

2020-12-15 18:20 UTC, nelder9 commented on src/utils/render.js
> +export const renderPosition = {
Аа это типа коллекция констант, поэтому с большой? (исправил)

2020-12-15 18:28 UTC, abeluzhenko commented on src/utils/render.js
> +export const renderPosition = {
Это отдельная категория - перечисления, для них свой критерий: https://up.htmlacademy.ru/ecmascript/13/criteries#b7

2020-12-15 18:50 UTC, abeluzhenko approved these changes

2020-12-15 19:00 UTC, merged