Module7 task1
htmlacademy-ecmascript/1410513-big-trip-13 pull request #12
Opened 2020-12-25 19:36 UTC by nelder9

2020-12-26 09:37 UTC, abeluzhenko requested changes
Есть небольшие проблемы с форматированием, попробуй перед пушем прогонять через prettier, это гораздо проще, чем выставлять все руками.

2020-12-26 09:37 UTC, abeluzhenko commented on src/model/events.js
> +    ];
Думаю, здесь лучше использовать `filter`:
```suggestion
    this._events = this._events.filter((_, i) => i !== index);
```

2020-12-26 09:37 UTC, abeluzhenko commented on src/presenter/board.js
> +    if (this._tripEventsSortComponent !== null) {
Мне кажется, проверка лишняя. Ничего страшного, если занулится null

2020-12-26 09:37 UTC, abeluzhenko commented on src/presenter/board.js
> +  } = {}) {
Не пойму, зачем здесь параметр объект? Думаю, пока что достаточно параметра по-умолчанию.

2020-12-26 09:37 UTC, abeluzhenko commented on src/presenter/event.js
> +} from "../const.js";
[nit] Здесь кажется как-то не так сработало автоформатирование.

2020-12-26 09:37 UTC, abeluzhenko commented on src/presenter/event.js
> +        event);
```suggestion
        event
   );
```

2020-12-26 09:37 UTC, abeluzhenko commented on src/presenter/filter.js
> +// import {filter} from "../utils/filter.js";
Лучше сразу удалять неиспользуемый код, его всегда можно восстановить из истории

2020-12-26 09:37 UTC, abeluzhenko commented on src/utils/filter.js
> +export const filter = {
Этот map - глобальная константа, нужно дать ему имя в UPPER_CASE. 
И хорошо бы дать более понятное имя, или не использовать мап напрямую, а, например, через хелпер `filterBy`, который также мог бы возврашать identity-функцию, если передано некорректное поле для сортировки.

2020-12-26 09:37 UTC, abeluzhenko commented on src/view/trip-filters.js
> +  );
Здесь что-то не то с форматированием)

2020-12-26 09:37 UTC, abeluzhenko commented on src/view/trip-item-edit.js
> +    this._datepicker = null;
Ниже уже нулится, можно это удалить

2020-12-26 09:37 UTC, abeluzhenko commented on src/view/trip-item-edit.js
> +    if (this._datepicker) {
[nit] Код очистки `_datepicker` дублируется, может стоит завести метод `removeDatepicker`. Особенно, если понадобится это сделать в 3ий раз.

2020-12-26 09:37 UTC, abeluzhenko commented on src/utils/event.js
> +  return date === null ? false : dayjs().isAfter(date, `MMM D`);
Думаю здесь проще использовать short-circuit
```suggestion
  return date && dayjs().isAfter(date, `MMM D`);
```

2021-01-01 10:53 UTC, nelder9 commented on src/model/events.js
> +    ];
+

2021-01-01 11:35 UTC, nelder9 commented on src/view/trip-item-edit.js
> +    if (this._datepicker) {
Вместо if (this._datepicker) {
      this._datepicker.destroy();
      this._datepicker = null;
    }  => писать просто что-то вроде removeDatepicker() , а эту функцию сохранить в utils? а что такое [nit] ?

2021-01-01 11:35 UTC, nelder9 commented on src/model/events.js
> +    ];
done

2021-01-01 11:35 UTC, nelder9 commented on src/presenter/board.js
> +    if (this._tripEventsSortComponent !== null) {
done

2021-01-01 11:36 UTC, nelder9 commented on src/presenter/event.js
> +} from "../const.js";
В одну строчку сделать надо? import {ESC} from "../const.js";

2021-01-01 11:36 UTC, nelder9 commented on src/presenter/event.js
> +        event);
done

2021-01-01 11:36 UTC, nelder9 commented on src/utils/filter.js
> +export const filter = {
done

2021-01-01 11:37 UTC, nelder9 commented on src/view/trip-filters.js
> +  );
Не вижу где именно)))))

2021-01-01 11:37 UTC, nelder9 commented on src/view/trip-item-edit.js
> +    this._datepicker = null;
done

2021-01-01 11:38 UTC, nelder9 commented on src/utils/event.js
> +  return date === null ? false : dayjs().isAfter(date, `MMM D`);
short-circuit это - название оператора && (и) ?

исправил

2021-01-01 16:59 UTC, abeluzhenko commented on src/presenter/event.js
> +} from "../const.js";
Да, лучше в одну строчку

2021-01-01 17:01 UTC, abeluzhenko commented on src/view/trip-filters.js
> +  );
input на одном уровне с div-ом, как будто у всего, что ниже инпута пропал отступ

2021-01-01 17:05 UTC, abeluzhenko commented on src/view/trip-item-edit.js
> +    if (this._datepicker) {
Не в utils, а в метод класса, т.к. это очень специфический метод. 
Nit - значит "придирка" (nitpick), т.е. это то, что ревьюверу не очень нравится, но не критично. Это исправлять не обязательно, на усмотрение автора.

2021-01-01 17:08 UTC, abeluzhenko commented on src/utils/event.js
> +  return date === null ? false : dayjs().isAfter(date, `MMM D`);
Нет, сам оператор так и называют обычно "и". 
Short-circuit это именно код вида `a && b`, когда `b` не выполнится, если `a == false`, то есть произойдет "короткое замыкание" раньше, чем интерпретатор дойдет до выполнения\проверки b

2021-01-01 17:09 UTC, abeluzhenko approved these changes

2021-01-01 17:09 UTC, merged