удалил моки, данные приходят с сервера, офферы пока не сделал
htmlacademy-ecmascript/1410513-big-trip-13 pull request #13
Opened 2021-01-08 18:27 UTC by nelder9

2021-01-11 09:30 UTC, abeluzhenko requested changes

2021-01-11 09:30 UTC, abeluzhenko commented on src/view/trip-item.js
> +const diffTime = (dateFrom, dateTo) => {
А зачем нужен этот хелпер? Есть же `dayjs(...).diff(...)`, который может то же самое (https://day.js.org/docs/en/display/difference)

2021-01-11 09:30 UTC, abeluzhenko commented on src/model/events.js
> +    return adaptedEvent;
Думаю, здесь стоит просто перечислить поля, которые нам нужны, явное объявление всегда лучше скрытого и получится гораздо короче:
```suggestion
    return {
      id: event.id,
      destination: event.destination,
      offers: event.offers,
      type: event.type,
      price: event.base_price,
      isFavorite: event.is_favorite,
      dateFrom: event.date_from,
      dateTo: event.date_to
    };
```

2021-01-11 09:30 UTC, abeluzhenko commented on src/model/events.js
> +    return adaptedEvent;
Здесь примерно так-же:
```suggestion
    return {
      id: event.id,
      destination: event.destination,
      offers: event.offers,
      type: event.type,
      [`base_price`]: event.price,
      [`is_favorite`]: event.isFavorite,
      [`date_from`]: event.dateFrom,
      [`date_to`]: event.dateTo,
    };
```
Плюс, можно избавиться от дублирования общих полей, создав хелпер `getCommonFields`, который бы возвращал объект с `id, type, offers, destination`

2021-01-11 09:30 UTC, abeluzhenko commented on src/presenter/event-new.js
> +    // this._destroyCallback = null;
`_destroyCallback` нигде не используется, можно его удалить

2021-01-18 10:18 UTC, nelder9 commented on src/presenter/event-new.js
> +    // this._destroyCallback = null;
удалил

2021-01-18 10:18 UTC, nelder9 commented on src/model/events.js
> +    return adaptedEvent;
поправил

2021-01-18 10:18 UTC, nelder9 commented on src/model/events.js
> +    return adaptedEvent;
поправил

2021-01-18 10:24 UTC, nelder9 commented on src/view/trip-item.js
> +const diffTime = (dateFrom, dateTo) => {
а там в зависимости от разницы надо формат отображения менять - сутки часы минуты

2021-01-19 17:45 UTC, abeluzhenko requested changes

2021-01-19 17:45 UTC, abeluzhenko commented on src/utils/filter.js
>    [FilterType.EVERYTHING]: (events) => events,
Сразу не заметил, но надо подправить. Здесь получается неконсистентно, т.к. в остальных случаях возвращается новый массив, а в этом тот же. Можно случайно его изменить, что может привести к ошибке.
```suggestion
  [FilterType.EVERYTHING]: (events) => [...events],
```

2021-01-19 17:45 UTC, abeluzhenko commented on src/presenter/board.js
>      this._renderEvents(this._getEvents());
Незачем снова вызывать `this._getEvents()`, можно передать `events`

2021-01-20 06:06 UTC, merged