настроил флетпикер
htmlacademy-ecmascript/1410513-big-trip-13 pull request #15
Opened 2021-01-22 18:06 UTC by nelder9

2021-01-24 19:29 UTC, abeluzhenko requested changes

2021-01-24 19:29 UTC, abeluzhenko commented on src/view/trip-item-edit.js
> +      dateFrom: dayjs(userDate).hour(23).minute(59).second(59).toDate()
А зачем такое время задано?

2021-01-24 19:29 UTC, abeluzhenko commented on src/utils/event.js
> +export const humanizeEditEventTime = (dueDate) => {
[nit] кажется, лучше назвать `formatEditEventTime`

2021-01-26 19:44 UTC, nelder9 commented
Не могу понять почему при вызове функции _typeChangeHandler , не происходит повторная отрисовка других офферов

2021-01-27 18:02 UTC, abeluzhenko requested changes

2021-01-27 18:02 UTC, abeluzhenko commented on src/view/trip-item-edit.js
> +      currentAvailableOffers = serverOffers[0].offers;
Неправильно полагаться на индекс, формат данных с бекенда может часто меняться. У элементов есть поле type, можно фильтровать достуные оферы по нему: `return serverOffers.filter(it => it.type === type)`

2021-01-29 05:47 UTC, abeluzhenko requested changes

2021-01-29 05:47 UTC, abeluzhenko commented on src/presenter/event.js
> +    // this._replaceEditToTrip();
Давай удалим, это не будет нужно
```suggestion
    // this._replaceEditToTrip();
```

2021-01-29 05:47 UTC, abeluzhenko commented on src/presenter/event.js
> +  constructor(eventListContainer, changeData, changeMode, _destinationsModel, _offersModel) {
Параметры функции не стоит именовать с преффиксом _, т.к. есть конвенция по которой так отмечают неиспользуемые параметры, давай уберем _

2021-01-29 15:41 UTC, abeluzhenko approved these changes

2021-01-29 15:41 UTC, merged