создал два презентера, создал датабиндинг по кнопки favorite, завел п…
htmlacademy-ecmascript/1410513-big-trip-13 pull request #9
Opened 2020-12-09 20:52 UTC by nelder9

…аттерн Наблюдатель

2020-12-10 19:49 UTC, abeluzhenko requested changes

2020-12-10 19:49 UTC, abeluzhenko commented on src/mock/event.js
> +const generateId = () => Date.now() + parseInt(Math.random() * 10000, 10);
Лучше использовать `Math.ceil` или `Math.floor`, `parseInt` больше похоже на хак.

2020-12-10 19:49 UTC, abeluzhenko commented on src/utils/common.js
> +export const updateItem = (items, update) => {
Здесь, мне кажется, не очень удачное имя. Функция не обновляет item, она возвращает обновленный список item-ов, причем не мутируя исходный (что отлично). Я думаю лучше назвать ее `getUpdatedItems`

2020-12-10 19:49 UTC, abeluzhenko commented on src/view/trip-item.js
> +  const favoriteClassName = isFavorite
Получается, в случае, если isFavorite === false, то в класс `event__favorite-btn` в элементе продублируется.
Нужно либо добавить `event__favorite-btn` + в начало выражения и убрать его из шаблона,
либо здесь возвращать пустую строку вместо `event__favorite-btn`

2020-12-10 21:13 UTC, nelder9 commented on src/mock/event.js
> +const generateId = () => Date.now() + parseInt(Math.random() * 10000, 10);
Ну насколько я понял, в реальных проектах - такой способ генерации рандомного айди нельзя использовать, нужно применять специальный библиотеки, типа nanoid... тут умышлено сделано в видел такого костыля... как я это понял...

2020-12-10 21:14 UTC, nelder9 commented on src/view/trip-item.js
> +  const favoriteClassName = isFavorite
ага, действительно дублировался, поставил пустую строку

2020-12-10 21:15 UTC, nelder9 commented on src/utils/common.js
> +export const updateItem = (items, update) => {
Исправил

2020-12-12 08:38 UTC, abeluzhenko approved these changes

2020-12-12 08:38 UTC, merged